# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = ["github.com/iovisor/gobpf/bcc"]
ignored = []

[[constraint]]
  branch = "master"
  name = "github.com/iovisor/gobpf"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "7b2c5ac9fc04fc5efafb60700713d4fa609b777b"
